# fly.toml app configuration file generated for boilerplate-project-urlshortener on 2024-04-03T15:08:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boilerplate-project-urlshortener'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
