name: Testing

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "MONGODB_URI=$MONGODB_URI" >> $GITHUB_ENV
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run tests
        run: npm test
